### ISSUE TITLE
Error when executing a command from the console

### ISSUE THREAD

**Issue by Matocolotoe** [IHasName/CustomHeads#11]
When doing "heads reload" from the console, this happens
CustomHeads version : 2.9.3
Spigot version : 1.8.8

```
[15:46:28] [Server thread/WARN]: Unexpected exception while parsing console command "heads reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'heads' in plugin CustomHeads v2.9.3
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.DedicatedServer$5.evaluate(DedicatedServer.java:650) [Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.DedicatedServer$5.evaluate(DedicatedServer.java:1) [Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at org.bukkit.craftbukkit.v1_8_R3.util.Waitable.run(Waitable.java:24) [Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:728) [Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:653) [Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:556) [Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.command.CraftRemoteConsoleCommandSender cannot be cast to org.bukkit.entity.Player
	at de.mrstein.customheads.stuff.CHCommand.onCommand(CHCommand.java:76) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot-v1_8_8.jar:git-Spigot-0359393-9cd1111]
	... 11 more
```

**Comment by IHasName** [comment]
hmm seems that the Command is send through the CraftRemoteConsoleCommandSender.
I'll try to change [this](https://github.com/MrSteinMC/CustomHeads/blob/master/src/main/java/de/mrstein/customheads/stuff/CHCommand.java#L49) to ``if(!(sender instanceof Player))``

**Comment by IHasName** [comment]
Fixed but couldn't Update anything because of the Economy Support im working on
