### ISSUE TITLE
/heads categories throws error

### ISSUE THREAD

**Issue by Aurelien30000** [IHasName/CustomHeads#27]
## Issue Description

Error throw multiple times using /heads categories:

```
[00:41:03 WARN]: [CustomHeads] Could not send JSON-Message to Player
java.lang.NoSuchMethodException: net.minecraft.server.v1_16_R3.PacketPlayOutChat.<init>(net.minecraft.server.v1_16_R3.IChatBaseComponent)
        at java.lang.Class.getConstructor0(Class.java:3349) ~[?:?]
        at java.lang.Class.getConstructor(Class.java:2151) ~[?:?]
        at de.likewhat.customheads.utils.Utils.sendJSONMessage(Utils.java:635) ~[?:?]
        at de.likewhat.customheads.utils.stuff.CHCommand.onCommand(CHCommand.java:236) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:806) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2091) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1902) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1855) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1192) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1185) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1161) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1005) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Tuinity-"2f298d3"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

Thanks! ;)

## Infos
  - Plugin Version: 3.0.2
  - Minecraft Version (ex. Spigot 1.8, Paper 1.12.2): Paper 1.16.5

**Comment by IHasName** [comment]
Seems like a Version Issue. I'll be fixing it in an upcoming Version ^^

**Comment by IHasName** [comment]
Fixed by latest Version
