### ISSUE TITLE
Console spam in 1.17

### ISSUE THREAD

**Issue by John-H-Smith** [IHasName/CustomHeads#29]
Just to help you fixing some errors, this error is spammed in the console:

```
[18:38:54] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.NBTTagCompound
[18:38:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[18:38:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[18:38:54] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[18:38:54] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[18:38:54] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[18:38:54] [Server thread/WARN]: 	at de.likewhat.customheads.utils.Utils.getMCServerClassByName(Utils.java:664)
[18:38:54] [Server thread/WARN]: 	at de.likewhat.customheads.utils.reflection.TagEditor.setTags(TagEditor.java:63)
[18:38:54] [Server thread/WARN]: 	at de.likewhat.customheads.utils.reflection.TagEditor.addTags(TagEditor.java:92)
[18:38:54] [Server thread/WARN]: 	at de.likewhat.customheads.utils.reflection.TagEditor.addTags(TagEditor.java:83)
[18:38:54] [Server thread/WARN]: 	at de.likewhat.customheads.category.CustomHead.<init>(CustomHead.java:25)
[18:38:54] [Server thread/WARN]: 	at de.likewhat.customheads.category.Category$Serializer.deserialize(Category.java:175)
[18:38:54] [Server thread/WARN]: 	at de.likewhat.customheads.category.Category$Serializer.deserialize(Category.java:145)
[18:38:54] [Server thread/WARN]: 	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
[18:38:54] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:887)
[18:38:54] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:952)
[18:38:54] [Server thread/WARN]: 	at com.google.gson.Gson.fromJson(Gson.java:925)
[18:38:54] [Server thread/WARN]: 	at de.likewhat.customheads.category.CategoryManager.<init>(CategoryManager.java:65)
[18:38:54] [Server thread/WARN]: 	at de.likewhat.customheads.CustomHeads.reloadTranslations(CustomHeads.java:94)
[18:38:54] [Server thread/WARN]: 	at de.likewhat.customheads.CustomHeads.loadRest(CustomHeads.java:338)
[18:38:54] [Server thread/WARN]: 	at de.likewhat.customheads.CustomHeads.onEnable(CustomHeads.java:282)
[18:38:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:38:54] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[18:38:54] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[18:38:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518)
[18:38:54] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432)
[18:38:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643)
[18:38:54] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:304)
[18:38:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1118)
[18:38:54] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[18:38:54] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[18:38:54] [Server thread/WARN]: [CustomHeads] Failed to save Tags to Item
java.lang.NullPointerException: Cannot invoke "java.lang.Class.newInstance()" because the return value of "de.likewhat.customheads.utils.Utils.getMCServerClassByName(String)" is null
	at de.likewhat.customheads.utils.reflection.TagEditor.setTags(TagEditor.java:63) ~[?:?]
	at de.likewhat.customheads.utils.reflection.TagEditor.addTags(TagEditor.java:92) ~[?:?]
	at de.likewhat.customheads.utils.reflection.TagEditor.addTags(TagEditor.java:83) ~[?:?]
	at de.likewhat.customheads.category.CustomHead.<init>(CustomHead.java:25) ~[?:?]
	at de.likewhat.customheads.category.Category$Serializer.deserialize(Category.java:175) ~[?:?]
	at de.likewhat.customheads.category.Category$Serializer.deserialize(Category.java:145) ~[?:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at de.likewhat.customheads.category.CategoryManager.<init>(CategoryManager.java:65) ~[?:?]
	at de.likewhat.customheads.CustomHeads.reloadTranslations(CustomHeads.java:94) ~[?:?]
	at de.likewhat.customheads.CustomHeads.loadRest(CustomHeads.java:338) ~[?:?]
	at de.likewhat.customheads.CustomHeads.onEnable(CustomHeads.java:282) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:643) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:304) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1118) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[patched_1.17.jar:git-Paper-"4e2f0be"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

## Infos
  - Plugin Version: CustomHeads version 3.0.2
  - Minecraft Version: Paper version git-Paper-"4e2f0be" (MC: 1.17) (Implementing API version 1.17-R0.1-SNAPSHOT)

**Comment by IHasName** [comment]
1.17 isn't supported yet.
You can join my Discord to know when its out

**Comment by John-H-Smith** [comment]
I know, I just want to let you know so you have to test less ;-)

**Comment by IHasName** [comment]
Yeah its basically the NMS im doing and 1.17 either changed or removed this specific Function
