### ISSUE TITLE
Task #3526 for CustomHeads v2.7 generated an exception

### ISSUE THREAD

**Issue by DimitarDechew** [IHasName/CustomHeads#3]
[CustomHeads] Task #3526 for CustomHeads v2.7 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class de.mrstein.util.GameProfileBuilder
        at de.mrstein.CustomHeads$3.run(CustomHeads.java:101) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-c3c767f-33d5de3]
        at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:709) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:634) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:537) [spigot.jar:git-Spigot-c3c767f-33d5de3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]

**Comment by IHasName** [comment]
Try redownloading the Plugin
