### ISSUE TITLE
java.lang.IllegalStateException: Not a JSON Object: null

### ISSUE THREAD

**Issue by TimDegraaf** [IHasName/CustomHeads#37]
## Issue Description
12.04 03:42:19 [Server] WARN Plugin CustomHeads v3.0.4 generated an exception while executing task 89
12.04 03:42:19 [Server] INFO java.lang.IllegalStateException: Not a JSON Object: null
12.04 03:42:19 [Server] INFO at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:91) ~[gson-2.8.8.jar:?]
12.04 03:42:19 [Server] INFO at de.likewhat.customheads.utils.PlayerWrapper.clearCache(PlayerWrapper.java:94) ~[CustomHeads (4).jar:?]
12.04 03:42:19 [Server] INFO at de.likewhat.customheads.CustomHeads$4.run(CustomHeads.java:404) ~[CustomHeads (4).jar:?]
12.04 03:42:19 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1566]
12.04 03:42:19 [Server] INFO at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.1.jar:git-Purpur-1566]
12.04 03:42:19 [Server] INFO at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.1.jar:git-Purpur-1566]
12.04 03:42:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
12.04 03:42:19 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
12.04 03:42:19 [Server] INFO at java.lang.Thread.run(Thread.java:833) ~[?:?]
12.04 03:42:19 [Server] INFO Removed 1 old log files.
## Infos
  - Plugin Version: 3.0.4
  - Minecraft Version 1.18.1

**Comment by IHasName** [comment]
Probably a malformed Player Data File
Try validating it with a Json Validator and let me know what that gives you

**Comment by IHasName** [comment]
Closing due to inactivity

Reopen if the Issue still persists
