### ISSUE TITLE
Support for 1.19

### ISSUE THREAD

**Issue by sujyrokimora** [IHasName/CustomHeads#41]
Add Support for 1.19

**Comment by IHasName** [comment]
Working on it ^^

**Comment by ChrissW-R1** [comment]
Currently we get this error:

```
[00:36:09] [Server thread/INFO]: [CustomHeads] Enabling CustomHeads v3.0.6*
[00:36:09] [Server thread/INFO]: [CustomHeads] Using LATEST as Version Handler
[00:36:09] [Server thread/INFO]: [CustomHeads] Warning : Hrm. Seems like CustomHeads wasn't tested on this Minecraft Version (v1_19_R1) yet...
[00:36:09] [Server thread/INFO]: [CustomHeads] Warning : Feel free to join my Discord to know when it gets updated
[00:36:09] [Server thread/INFO]: [CustomHeads] Loading Economy Handler...
[00:36:09] [Server thread/INFO]: [CustomHeads] Successfully loaded Economy Handler: Vault using EssentialsX Economy
[00:36:09] [Server thread/ERROR]: [CustomHeads] Failed to cache Class
java.lang.ClassNotFoundException: net.minecraft.network.protocol.game.PacketPlayOutChat
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:383) ~[?:?]
	at java.lang.Class.forName(Class.java:376) ~[?:?]
	at de.likewhat.customheads.utils.reflection.helpers.ReflectionUtils.checkCachedClassname(ReflectionUtils.java:227) ~[CustomHeads-3.0.6.jar:?]
	at de.likewhat.customheads.utils.reflection.helpers.ReflectionUtils.getMCServerClassByName(ReflectionUtils.java:211) ~[CustomHeads-3.0.6.jar:?]
	at de.likewhat.customheads.utils.reflection.helpers.collections.ReflectionClassCollection.<clinit>(ReflectionClassCollection.java:7) ~[CustomHeads-3.0.6.jar:?]
	at de.likewhat.customheads.utils.reflection.helpers.collections.ReflectionMethodCollection.<clinit>(ReflectionMethodCollection.java:21) ~[CustomHeads-3.0.6.jar:?]
	at de.likewhat.customheads.utils.ItemEditor.setTexture(ItemEditor.java:156) ~[CustomHeads-3.0.6.jar:?]
	at de.likewhat.customheads.utils.JsonToItem.convertFromJson(JsonToItem.java:55) ~[CustomHeads-3.0.6.jar:?]
	at de.likewhat.customheads.category.Category$Serializer.deserialize(Category.java:163) ~[CustomHeads-3.0.6.jar:?]
	at de.likewhat.customheads.category.Category$Serializer.deserialize(Category.java:143) ~[CustomHeads-3.0.6.jar:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:963) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1034) ~[gson-2.8.9.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:1006) ~[gson-2.8.9.jar:?]
	at de.likewhat.customheads.category.CategoryManager.load(CategoryManager.java:74) ~[CustomHeads-3.0.6.jar:?]
	at de.likewhat.customheads.CustomHeads.reloadTranslations(CustomHeads.java:102) ~[CustomHeads-3.0.6.jar:?]
	at de.likewhat.customheads.CustomHeads.loadRest(CustomHeads.java:360) ~[CustomHeads-3.0.6.jar:?]
	at de.likewhat.customheads.CustomHeads.onEnable(CustomHeads.java:303) ~[CustomHeads-3.0.6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-138]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[paper-1.19.2.jar:git-Paper-138]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-138]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by IHasName** [comment]
New Version is out
